CC=cc68x
CFLAGS=-O -g
FONT_OBJS=lib/unifont.c lib/depixel.o
OBJS=main.o raster.o bitmaps.o  $(FONT_OBJS)


main: $(OBJS)
	$(CC) $(OBJS) -o $@

.PHONY: test clean
test: raster.t btmaps.t
	raster.t
	btmaps.t
	@$(ECHO) Finished Running Tests.


clean:
	$(RM) *.o *.t main

unity.o:
	$(CC) -c lib/unity.c -o unity.o

# Test Template:
# <mod>.t: <mod test>.o unity.o
#	$(CC) $< unity.o -o $@
#	$@							# Run the test

raster.t: raster.o raster_t.o unity.o
	$(CC) $^ -o $@


btmaps.t: bitmaps.o btmaps_t.o unity.o
	$(CC) $^ -o $@



