# Generates the gnu unifont chars for printable 7 bit ascii characters

BASE=$(git rev-parse --show-toplevel)

HEXFILE="$BASE/lib/unifont-16.0.02.hex"
OUTFILE="$BASE/lib/unifont.c"

function main() {
    printf "/* THIS CODE IS GENERATED DO NOT EDIT \n"
    printf "   GENERATED by tools/gen_unifont.sh .*/"


    printf '#include "../font.h" \n const u32 glyphs[128][4] = {'

    head -n 128 $HEXFILE  \
        | cut -d ':' -f2 \
        | sed 's/^.\{64\}$/0/' \
        | while IFS= read -r line; do
            echo "$line" | fold -w 8 | sed 's/^/0x/' | paste -sd ',' -
        done \
        | sed 's/.*/{&},/'
    printf '};'
}

main | clang-format > $OUTFILE
